### ISSUE TITLE
Documentation roadmap

### ISSUE THREAD

**Issue by merrymercy** [alpa-projects/alpa#310]
- End-user Tutorials
   - [x] MLP with synthetic data @reinaw1012 
   - [ ] BERT with real data loader
- Developer tutorials
   - [x] Architecture overview
   - [ ] Auto sharding code walk through
   - [ ] Pipeline code walk through 
- Website
  - [x] create a documentation website
