### ISSUE TITLE
While loop support in shard_parallel

### ISSUE THREAD

**Issue by merrymercy** [alpa-projects/alpa#400]
## Background
Currently, the [auto-sharding pass](https://github.com/alpa-projects/tensorflow-alpa/blob/master/tensorflow/compiler/xla/service/spmd/auto_sharding.cc) for intra-op parallelism does not support any control flow instructions (e.g., while and if). For example, the function `compute_alpa()` below will cause assertion errors.

```python
import jax
import jax.numpy as jnp
import numpy as np

import alpa

N = 1024
n_iter = 5

x = np.ones((N, N), dtype=np.float32)
w = np.ones((N, N), dtype=np.float32)


def compute_numpy():
    y = x
    for i in range(n_iter):
        y = y @ w
    return y


def func(a, b):
    init_state = (0, x, w)
    cond_func = lambda state: state[0] < n_iter
    body_func = lambda state: (state[0] + 1, state[1] @ state[2], state[2])

    final_state = jax.lax.while_loop(cond_func, body_func, init_state)
    return final_state[1]


def compute_jax_jit():
    return jax.jit(func)(x, w)


def compute_alpa():
    return alpa.parallelize(func)(x, w)


# Check correctness
expected = compute_numpy()
actual = compute_jax_jit()
np.testing.assert_allclose(expected, actual)

# Inspect the HLO IR
hlo_text = jax.jit(func).lower(x, w).compile().compiler_ir()[0].to_string()
print(hlo_text)

# Currently, alpa does not support while loop. The following function
# causes assertion errors. We want to support it.
# actual = compute_alpa()
# np.testing.assert_allclose(expected, actual)
```
To support them, we need to correctly handle `HloOpcode::kWhile` and `HloOpcode::kConditional` in the auto-sharding pass.

## Todo
- [ ] Learn the auto-sharding pass
    - [ ] Read the reference materials 
    - [ ] Understand the test cases in `tests/test_auto_sharding_basic.py` and `tests/test_auto_sharding_mlp.py`
        -  The call stack is a little complicated with mixed python code and c++ code. The core entry point is [alpa/shard_parallel/auto_sharding.py](https://github.com/alpa-projects/alpa/blob/2945fc4ea29e16ba7014e165e85624ed6d12b137/alpa/shard_parallel/auto_sharding.py#L128) and [tensorflow-alpa/compiler/xla/service/spmd/auto_sharding.cc](https://github.com/alpa-projects/tensorflow-alpa/blob/a61c448887d4d3962189342a3f398497aab53abb/tensorflow/compiler/xla/service/spmd/auto_sharding.cc#L2071). You can run one test case and trace it from python to c++.
- [ ] Support while loop
    - We assume we know the length of the loop at compile time. As the first step, we can simply set the length as a fixed constant (e.g., 5). Latter, this can be improved by inferring from the code. Once we know the loop length, we can unroll the while loop when we build the cost graph. For example, we can multiply the costs of all nodes/edges in the while loop by the loop length.
    - Implement the above idea in `auto_sharding.cc` and fix all other errors. We should be able to run `compute_alpa`.
- [ ] Support if

## Reference
- XLA Operation Semantics: https://www.tensorflow.org/xla/operation_semantics
- Algorithm description: section 4 of https://arxiv.org/abs/2201.12023

**Comment by merrymercy** [comment]
cc @HeydrichBeillschmidt

**Comment by yf225** [comment]
I suspect `if` is a more commonly used control flow than `while`, and we can consider implementing `if` first.

@zhisbug suggested we can just map it to https://www.tensorflow.org/xla/operation_semantics#conditional for now and ignore the effect on training plan, and we can fix any imbalance issue later.

**Comment by merrymercy** [comment]
@HeydrichBeillschmidt Could you share a little bit about your progress?

**Comment by mmorinag127** [comment]
Is there any news on this topic?
I'm really want to use it with the alpa:)

**Comment by merrymercy** [comment]
https://github.com/alpa-projects/tensorflow-alpa/pull/124

**Comment by merrymercy** [comment]
@mmorinag127 WIP branch https://github.com/alpa-projects/tensorflow-alpa/pull/124
