### ISSUE TITLE
[PERF][REFACTOR] Use one uuid for all buffers of a tensor

### ISSUE THREAD

**Issue by ZYHowell** [alpa-projects/alpa#504]
## Background and Motivation

Currently, Alpa assigns a UUID for each remote device buffer, and thus a [distributed tensor](https://github.com/alpa-projects/alpa/blob/ef6df24f1c6603ce40ed78cf0837c2bee5ba64e7/alpa/device_mesh.py#L1382) with multiple remote buffers has multiple UUIDs and `RemoteBufferRef`s. Creating and deleting these objects is costly. However, since all operations are on the tensor level and each mesh worker executes SPMD programs, only one UUID is enough for a tensor. Using one UUID for all buffers of a tensor can reduce the runtime overhead by a constant factor. This is also what [Pathways](https://arxiv.org/pdf/2203.12533.pdf) does (in sec 4.2 client, they use sharded tensor equivalent to Alpa's DistributedArray).

## TODO
  - [x] Change the type of `MeshHostWorker.buffers`: From `Dict[int, DeviceArray]` to `Dict[int, Sequence[DeviceArray]]`.
    - Change the implementation of buffer-related methods in `MeshHostWorker`.
    - Move codes in `RemoteBufferRef` to `DistributedArray`.
    - Change return value of functions in `shard_arg_handlers`.
  - [x] ShardParallel: Rewrite `DriverExecutable.launch_on_driver` and `WorkerExecutable.execute_on_worker`'s pre- and post-process.
  - [x] CrossMeshResharding: Refactor cross-mesh resharding tasks' API.
    - Replace `buf_uuids` by `device_indices` in `MeshHostWorker`'s related functions.
  - [x] PipeshardParallel: Refactor `PipelineInstruction`.
